# Links to the papers
chen2024uni: "https://www.nature.com/articles/s41591-024-02857-3"
elnahhas2024stamp: "https://www.nature.com/articles/s41596-024-01047-2"
hie2022esm2: "https://www.biorxiv.org/content/10.1101/2022.12.21.521526v1"
hollmann2025tabpfn: "https://www.nature.com/articles/s41586-024-08328-6"
isensee2020nnunet: "https://www.nature.com/articles/s41592-020-01008-z"
smith2024flowmap: "https://arxiv.org/abs/2404.15259"
jiang2025medsss: "https://arxiv.org/abs/2501.12051"
kunes2023cytopus: "https://www.nature.com/articles/s41587-023-01940-3"
liang2023pathfinder: "https://www.nature.com/articles/s42256-023-00635-3"
lu2024conch: "https://www.nature.com/articles/s41591-024-02856-4"
ma2024medsam: "https://www.nature.com/articles/s41467-024-44824-z"
smith2024flowmap: "https://arxiv.org/abs/2404.15259"
verkuil2022esm1: "https://www.biorxiv.org/content/10.1101/2022.12.21.521521v1"
warner2024modernbert: "https://arxiv.org/abs/2412.13663"
xiang2025musk: "https://www.nature.com/articles/s41586-024-08378-w"
zhang2024biomedclip: "https://ai.nejm.org/doi/full/10.1056/AIoa2400640"
zhou2023retfound: "https://www.nature.com/articles/s41586-023-06555-x"
pocock2022tiatoolbox: "https://www.nature.com/articles/s43856-022-00186-5"
lenz2025cobra: "https://arxiv.org/abs/2411.13623"
wiest2024llm: "https://www.medrxiv.org/content/10.1101/2024.09.02.24312917"
zou2024textgrad: "https://arxiv.org/abs/2406.07496"
yuksekgonul2024textgrad: "https://arxiv.org/abs/2406.07496"
neidlinger2025eagle: "https://arxiv.org/abs/2502.13027"
wasserthal2023totalsegmentator: "https://pubs.rsna.org/doi/10.1148/ryai.230024"
zigutyte2024mopadi: "https://www.biorxiv.org/content/10.1101/2024.10.29.620913v2"
