name: cobra_heatmaps # Name of the task. Should correspond to the name of the folder.
requires: cuda
repo:
  name: COBRA # Name of the repository.
  url: "https://github.com/KatherLab/COBRA" # URL of the repository.
  commit: null # Commit hash of the repository (optional, default is the latest commit). It is recommended to use a specific commit to ensure reproducibility.
  # branch: main # Branch of the repository (optional)
  env:
    - name: HF_TOKEN
      value: "${env:HF_TOKEN}"
papers: [lenz2025cobra] # List of papers that this task is based on. Papers are specified by their IDs in the papers.bib file.
category: pathology # Category of the task.
description: Create unsupervised heatmaps using COBRA. The provided tile features have 1.0 mpp (224 microns / 224 px per patch).  # Description of the task. This should be 1-3 sentences in length, explaining to the LLM what this tool should do.
arguments:
  - name: output_dir
    description: Path to the output folder where the features will be saved
    type: str
  - name: slide_dir
    description: Path to the input folder containing the WSIs
    type: str
  - name: tile_features_dir
    description: Path to the input folder containing the tile features
    type: str
returns:
  - name: num_heatmaps
    description: The number of heatmaps that were generated
    type: int
  - name: byte_size_heatmaps
    description: The number of total bytes of the generated heatmaps 
    type: int
example:
  arguments:
    - name: output_dir
      value: /mount/output/cobra_heatmaps-crc
    - name: tile_features_dir
      value: /mount/input/TCGA-CRC-Virchow2-features-10x
    - name: slide_dir 
      value: /mount/input/crc-wsi
  mount:
    # In this section, you can specify files or folders that should be mounted from the data directory to the container (at "/mount/input" in the container).
    # Each mount is a dictionary with the keys "source" and "target", where "source" is the path to the file or folder in the data directory and "target" is the path to the file or folder in the container.
    # For example, the following line mounts the file "TUM-TCGA-ACRLPPQE.tif" from the data directory to the container, placing it at the path "/mount/input/TUM-TCGA-ACRLPPQE.tif" in the container.
    - source: TCGA-CRC-Virchow2-features-10x
      target: TCGA-CRC-Virchow2-features-10x
    - source: crc-wsi
      target: crc-wsi
test_invocations:
  # Below, we define test invocations for the task.
  # Each test invocation is a dictionary with the keys "name", "arguments", and "mount", like the example invocation above (with the addition of the "name" key).
  # The test invocations can be used in the unit tests to check that the task is working as expected.
  # Below, we define 3 test invocations for the task, named "tif", "png", and "jpg". 
  # It is recommended that you define at least 3 test invocations (of course, you can choose any names you want).
  - name: crc
    arguments:
      - name: output_dir
        value: /mount/output/cobra_heatmaps-crc
      - name: tile_features_dir
        value: /mount/input/TCGA-CRC-Virchow2-features-10x
      - name: slide_dir 
        value: /mount/input/crc-wsi
    mount:
      - source: TCGA-CRC-Virchow2-features-10x
        target: TCGA-CRC-Virchow2-features-10x
      - source: crc-wsi
        target: crc-wsi
  - name: brca
    arguments:
      - name: output_dir
        value: /mount/output/cobra_heatmaps-brca
      - name: tile_features_dir
        value: /mount/input/TCGA-BRCA-Virchow2-features-10x
      - name: slide_dir 
        value: /mount/input/brca-wsi
    mount:
      - source: TCGA-BRCA-Virchow2-features-10x
        target: TCGA-BRCA-Virchow2-features-10x
      - source: brca-wsi
        target: brca-wsi
  - name: brca-single
    arguments:
      - name: output_dir
        value: /mount/output/cobra_heatmaps-brca-single
      - name: tile_features_dir
        value: /mount/input/TCGA-BRCA-Virchow2-features-10x
      - name: slide_dir 
        value: /mount/input/brca-wsi
    mount:
      - source: TCGA-BRCA-Virchow2-features-10x/TCGA-BH-A0HQ-01Z-00-DX1.0921FCEF-20A2-4D4B-A198-91AF9F6C814C.h5
        target: TCGA-BRCA-Virchow2-features-10x/TCGA-BH-A0HQ-01Z-00-DX1.0921FCEF-20A2-4D4B-A198-91AF9F6C814C.h5
      - source: brca-wsi/TCGA-BH-A0HQ-01Z-00-DX1.0921FCEF-20A2-4D4B-A198-91AF9F6C814C.svs
        target: brca-wsi/TCGA-BH-A0HQ-01Z-00-DX1.0921FCEF-20A2-4D4B-A198-91AF9F6C814C.svs