name: stamp_extract_features
repo:
  name: STAMP
  url: "https://github.com/KatherLab/STAMP"
  commit: 0042e6f
papers: [elnahhas2024stamp]
category: pathology
requires: cuda
description: Perform feature extraction using CTransPath with STAMP on a set of whole slide images, saving the resulting features to the specified output directory.
arguments:
  - name: output_dir
    description: Path to the output folder where the features will be saved
    type: str
  - name: slide_dir
    description: Path to the input folder containing the whole slide images
    type: str
returns:
  - name: num_processed_slides
    description: The number of slides that were processed
    type: int
example:
  arguments:
    - name: output_dir
      value: /mount/output/TCGA-BRCA-features
    - name: slide_dir
      value: /mount/input/TCGA-BRCA-SLIDES
  mount:
    - source: brca
      target: TCGA-BRCA-SLIDES
test_invocations:
  - name: crc
    arguments:
      - name: output_dir
        value: /mount/output/TCGA-CRC-features
      - name: slide_dir
        value: /mount/input/TCGA-CRC-SLIDES
    mount:
      - source: crc
        target: TCGA-CRC-SLIDES
  - name: crc_single
    arguments:
      - name: output_dir
        value: /mount/output/TCGA-CRC-features
      - name: slide_dir
        value: /mount/input/TCGA-CRC-SLIDES
    mount:
      - source: crc/TCGA-4N-A93T-01Z-00-DX1.82E240B1-22C3-46E3-891F-0DCE35C43F8B.svs
        target: TCGA-CRC-SLIDES/TCGA-4N-A93T-01Z-00-DX1.82E240B1-22C3-46E3-891F-0DCE35C43F8B.svs
  - name: brca_single
    arguments:
      - name: output_dir
        value: /mount/output/TCGA-BRCA-features
      - name: slide_dir
        value: /mount/input/TCGA-BRCA-SLIDES
    mount:
      - source: brca/TCGA-BH-A0BZ-01Z-00-DX1.45EB3E93-A871-49C6-9EAE-90D98AE01913.svs
        target: TCGA-BRCA-SLIDES/TCGA-BH-A0BZ-01Z-00-DX1.45EB3E93-A871-49C6-9EAE-90D98AE01913.svs
