name: flowmap_overfit_scene
repo:
  name: FlowMap
  url: "https://github.com/dcharatan/flowmap"
  commit: 578a515
papers: [smith2024flowmap]
category: 3d_vision
description: Overfit FlowMap on an input scene to determine camera extrinsics for each frame in the scene.
arguments:
  - name: input_scene
    description: Path to the directory containing the images of the input scene (just the image files, nothing else)
    type: str
returns:
  - name: "n"
    description: The number of images (frames) in the scene
    type: int
  - name: camera_extrinsics
    description: The camera extrinsics matrix for each of the n frames in the scene, must have a shape of nx4x4 (as a nested python list of floats)
    type: list
example:
  arguments:
    - name: input_scene
      value: /mount/input/llff_flower
  mount:
    - source: flowmap/llff_flower
      target: llff_flower
test_invocations:
  - name: llff_fern
    arguments:
      - name: input_scene
        value: /mount/input/llff_fern
    mount:
      - source: flowmap/llff_fern
        target: llff_fern
  - name: llff_orchids
    arguments:
      - name: input_scene
        value: /mount/input/llff_orchids
    mount:
      - source: flowmap/llff_orchids
        target: llff_orchids
